data=[
    {'name':'Bulbasaur', 
    'speed': 45, 
    'descript':'Seed Pokémon', 
    'ability':'Overgrow'},
    {'name':'Ivysaur', 
    'speed':60, 
    'descript':'Seed Pokémon', 
    'ability':'Overgrow'},
    {'name':'Venusaur', 
    'speed': 80, 
    'descript':'Seed Pokémon', 
    'ability':'Overgrow'},
    {'name':'Oddish', 
    'speed':30, 
    'descript':'Weed Pokémon', 
    'ability':'Chlorophyll'},
    {'name':'Gloom', 
    'speed': 40, 
    'descript':'Weed Pokémon', 
    'ability':'Chlorophyll'},
    {'name':'Vileplume', 
    'speed':50, 
    'descript':'Flower Pokémon', 
    'ability':'Chlorophyll'},
    {'name':'Paras', 
    'speed': 25, 
    'descript':'Mushroom Pokémon', 
    'ability':'Effect Spore'},
    {'name':'Parasect', 
    'speed':31, 
    'descript':'Mushroom Pokémon', 
    'ability':'Effect Spore'},
    {'name':'Bellsprout', 
    'speed': 41, 
    'descript':'Flower Pokémon', 
    'ability':'Chlorophyll'},
    {'name':'Weepinbell', 
    'speed':55, 
    'descript':'Flycatcher Pokémon', 
    'ability':'Chlorophyll'},
    {'name':'Victreebel', 
    'speed': 70, 
    'descript':'Flycatcher Pokémon',
    'ability':'Chlorophyll'},
    {'name':'Exeggcute', 
    'speed':42, 
    'descript':'Egg Pokémon', 
    'ability':'Chlorophyll'},
    {'name':'Exeggutor', 
    'speed': 55, 
    'descript':'Coconut Pokémon', 
    'ability':'Chlorophyll'},
    {'name':'Tangela', 
    'speed':61, 
    'descript':'Vine Pokémon', 
    'ability':'Chlorophyll'},
    {'name':'Chikorita', 
    'speed': 81, 
    'descript':'Leaf Pokémon', 
    'ability':'Overgrow'},
    {'name':'Bayleef', 
    'speed':63, 
    'descript':'Seed Pokémon', 
    'ability':'Overgrow'},
    {'name':'Meganium', 
    'speed':83, 
    'descript':'Herb Pokémon', 
    'ability':'Overgrow'},
    {'name':'Bellossom', 
    'speed':51, 
    'descript':'Flower Pokémon', 
    'ability':'Chlorophyll'},
    {'name':'Hoppip', 
    'speed':50, 
    'descript':'Cottonweed Pokémon', 
    'ability':'Chlorophyll'},
    {'name':'Skiploom', 
    'speed':82, 
    'descript':'Cottonweed Pokémon', 
    'ability':'Chlorophyll'},
    {'name':'Jumpluff', 
    'speed':110, 
    'descript':'Flower Pokémon', 
    'ability':'Chlorophyll'},
    {'name':'Sunkern', 
    'speed':33, 
    'descript':'Seed Pokémon', 
    'ability':'Chlorophyll'},
    {'name':'Sunflora', 
    'speed':34, 
    'descript':'Sun Pokémon', 
    'ability':'Chlorophyll'},
    {'name':'Celebi', 
    'speed':100, 
    'descript':'Time Travel Pokémon', 
    'ability':'Natural Cure'}]